#############################################################################
# Makefile for building: GxApps
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  GxApps.pro
# Template: subdirs
# Command: C:\Qt\5.15.2\mingw81_64\bin\qmake.exe -o Makefile GxApps.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\5.15.2\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.15.2\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.15.2\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-libUtil2 \
		sub-libExprEval \
		sub-libCwp \
		sub-libSegD \
		sub-GxLib \
		sub-SegDSeeMp \
		sub-SeiSeeMp


sub-libUtil2-qmake_all:  FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro
	cd libUtil2\ && $(MAKE) -f Makefile qmake_all
sub-libUtil2: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile
sub-libUtil2-make_first-ordered: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile 
sub-libUtil2-make_first: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile 
sub-libUtil2-all-ordered: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile all
sub-libUtil2-all: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile all
sub-libUtil2-clean-ordered: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile clean
sub-libUtil2-clean: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile clean
sub-libUtil2-distclean-ordered: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile distclean
sub-libUtil2-distclean: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile distclean
sub-libUtil2-install_subtargets-ordered: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile install
sub-libUtil2-install_subtargets: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile install
sub-libUtil2-uninstall_subtargets-ordered: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile uninstall
sub-libUtil2-uninstall_subtargets: FORCE
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile uninstall
sub-libExprEval-qmake_all: sub-libUtil2-qmake_all FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro
	cd libExprEval\ && $(MAKE) -f Makefile qmake_all
sub-libExprEval: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile
sub-libExprEval-make_first-ordered: sub-libUtil2-make_first-ordered  FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile 
sub-libExprEval-make_first: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile 
sub-libExprEval-all-ordered: sub-libUtil2-all-ordered  FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile all
sub-libExprEval-all: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile all
sub-libExprEval-clean-ordered: sub-libUtil2-clean-ordered  FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile clean
sub-libExprEval-clean: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile clean
sub-libExprEval-distclean-ordered: sub-libUtil2-distclean-ordered  FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile distclean
sub-libExprEval-distclean: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile distclean
sub-libExprEval-install_subtargets-ordered: sub-libUtil2-install_subtargets-ordered  FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile install
sub-libExprEval-install_subtargets: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile install
sub-libExprEval-uninstall_subtargets-ordered: sub-libUtil2-uninstall_subtargets-ordered  FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile uninstall
sub-libExprEval-uninstall_subtargets: FORCE
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile uninstall
sub-libCwp-qmake_all: sub-libExprEval-qmake_all FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro
	cd libCwp\ && $(MAKE) -f Makefile qmake_all
sub-libCwp: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile
sub-libCwp-make_first-ordered: sub-libExprEval-make_first-ordered  FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile 
sub-libCwp-make_first: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile 
sub-libCwp-all-ordered: sub-libExprEval-all-ordered  FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile all
sub-libCwp-all: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile all
sub-libCwp-clean-ordered: sub-libExprEval-clean-ordered  FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile clean
sub-libCwp-clean: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile clean
sub-libCwp-distclean-ordered: sub-libExprEval-distclean-ordered  FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile distclean
sub-libCwp-distclean: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile distclean
sub-libCwp-install_subtargets-ordered: sub-libExprEval-install_subtargets-ordered  FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile install
sub-libCwp-install_subtargets: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile install
sub-libCwp-uninstall_subtargets-ordered: sub-libExprEval-uninstall_subtargets-ordered  FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile uninstall
sub-libCwp-uninstall_subtargets: FORCE
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile uninstall
sub-libSegD-qmake_all: sub-libCwp-qmake_all FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro
	cd libSegD\ && $(MAKE) -f Makefile qmake_all
sub-libSegD: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile
sub-libSegD-make_first-ordered: sub-libCwp-make_first-ordered  FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile 
sub-libSegD-make_first: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile 
sub-libSegD-all-ordered: sub-libCwp-all-ordered  FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile all
sub-libSegD-all: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile all
sub-libSegD-clean-ordered: sub-libCwp-clean-ordered  FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile clean
sub-libSegD-clean: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile clean
sub-libSegD-distclean-ordered: sub-libCwp-distclean-ordered  FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile distclean
sub-libSegD-distclean: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile distclean
sub-libSegD-install_subtargets-ordered: sub-libCwp-install_subtargets-ordered  FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile install
sub-libSegD-install_subtargets: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile install
sub-libSegD-uninstall_subtargets-ordered: sub-libCwp-uninstall_subtargets-ordered  FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile uninstall
sub-libSegD-uninstall_subtargets: FORCE
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile uninstall
sub-GxLib-qmake_all: sub-libSegD-qmake_all FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro
	cd GxLib\ && $(MAKE) -f Makefile qmake_all
sub-GxLib: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile
sub-GxLib-make_first-ordered: sub-libSegD-make_first-ordered  FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile 
sub-GxLib-make_first: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile 
sub-GxLib-all-ordered: sub-libSegD-all-ordered  FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile all
sub-GxLib-all: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile all
sub-GxLib-clean-ordered: sub-libSegD-clean-ordered  FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile clean
sub-GxLib-clean: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile clean
sub-GxLib-distclean-ordered: sub-libSegD-distclean-ordered  FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile distclean
sub-GxLib-distclean: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile distclean
sub-GxLib-install_subtargets-ordered: sub-libSegD-install_subtargets-ordered  FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile install
sub-GxLib-install_subtargets: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile install
sub-GxLib-uninstall_subtargets-ordered: sub-libSegD-uninstall_subtargets-ordered  FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile uninstall
sub-GxLib-uninstall_subtargets: FORCE
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile uninstall
sub-SegDSeeMp-qmake_all: sub-GxLib-qmake_all FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro
	cd SegDSeeMp\ && $(MAKE) -f Makefile qmake_all
sub-SegDSeeMp: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile
sub-SegDSeeMp-make_first-ordered: sub-GxLib-make_first-ordered  FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile 
sub-SegDSeeMp-make_first: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile 
sub-SegDSeeMp-all-ordered: sub-GxLib-all-ordered  FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile all
sub-SegDSeeMp-all: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile all
sub-SegDSeeMp-clean-ordered: sub-GxLib-clean-ordered  FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile clean
sub-SegDSeeMp-clean: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile clean
sub-SegDSeeMp-distclean-ordered: sub-GxLib-distclean-ordered  FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile distclean
sub-SegDSeeMp-distclean: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile distclean
sub-SegDSeeMp-install_subtargets-ordered: sub-GxLib-install_subtargets-ordered  FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile install
sub-SegDSeeMp-install_subtargets: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile install
sub-SegDSeeMp-uninstall_subtargets-ordered: sub-GxLib-uninstall_subtargets-ordered  FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile uninstall
sub-SegDSeeMp-uninstall_subtargets: FORCE
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile uninstall
sub-SeiSeeMp-qmake_all: sub-SegDSeeMp-qmake_all FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro
	cd SeiSeeMp\ && $(MAKE) -f Makefile qmake_all
sub-SeiSeeMp: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile
sub-SeiSeeMp-make_first-ordered: sub-SegDSeeMp-make_first-ordered  FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile 
sub-SeiSeeMp-make_first: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile 
sub-SeiSeeMp-all-ordered: sub-SegDSeeMp-all-ordered  FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile all
sub-SeiSeeMp-all: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile all
sub-SeiSeeMp-clean-ordered: sub-SegDSeeMp-clean-ordered  FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile clean
sub-SeiSeeMp-clean: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile clean
sub-SeiSeeMp-distclean-ordered: sub-SegDSeeMp-distclean-ordered  FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile distclean
sub-SeiSeeMp-distclean: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile distclean
sub-SeiSeeMp-install_subtargets-ordered: sub-SegDSeeMp-install_subtargets-ordered  FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile install
sub-SeiSeeMp-install_subtargets: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile install
sub-SeiSeeMp-uninstall_subtargets-ordered: sub-SegDSeeMp-uninstall_subtargets-ordered  FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile uninstall
sub-SeiSeeMp-uninstall_subtargets: FORCE
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile uninstall

Makefile: GxApps.pro C:/Qt/5.15.2/mingw81_64/mkspecs/win32-g++/qmake.conf C:/Qt/5.15.2/mingw81_64/mkspecs/features/spec_pre.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/qdevice.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/device_config.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/sanitize.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/gcc-base.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/g++-base.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/angle.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/g++-win32.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/common/windows-desktop.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/qconfig.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/qt_functions.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/qt_config.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/toolchain.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/default_pre.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/resolve_config.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/default_post.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/precompile_header.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/warn_on.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/qmake_use.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/file_copies.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/win32/windows.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/exceptions.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/yacc.prf \
		C:/Qt/5.15.2/mingw81_64/mkspecs/features/lex.prf \
		GxApps.pro
	$(QMAKE) -o Makefile GxApps.pro
C:/Qt/5.15.2/mingw81_64/mkspecs/features/spec_pre.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/qdevice.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/device_config.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/sanitize.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/gcc-base.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/g++-base.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/angle.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/g++-win32.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/common/windows-desktop.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/qconfig.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_location.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/qt_functions.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/qt_config.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/toolchain.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/default_pre.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/resolve_config.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/default_post.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/precompile_header.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/warn_on.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/qmake_use.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/file_copies.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/win32/windows.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/testcase_targets.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/exceptions.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/yacc.prf:
C:/Qt/5.15.2/mingw81_64/mkspecs/features/lex.prf:
GxApps.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GxApps.pro

qmake_all: sub-libUtil2-qmake_all sub-libExprEval-qmake_all sub-libCwp-qmake_all sub-libSegD-qmake_all sub-GxLib-qmake_all sub-SegDSeeMp-qmake_all sub-SeiSeeMp-qmake_all FORCE

make_first: sub-libUtil2-make_first-ordered sub-libExprEval-make_first-ordered sub-libCwp-make_first-ordered sub-libSegD-make_first-ordered sub-GxLib-make_first-ordered sub-SegDSeeMp-make_first-ordered sub-SeiSeeMp-make_first-ordered  FORCE
all: sub-libUtil2-all-ordered sub-libExprEval-all-ordered sub-libCwp-all-ordered sub-libSegD-all-ordered sub-GxLib-all-ordered sub-SegDSeeMp-all-ordered sub-SeiSeeMp-all-ordered  FORCE
clean: sub-libUtil2-clean-ordered sub-libExprEval-clean-ordered sub-libCwp-clean-ordered sub-libSegD-clean-ordered sub-GxLib-clean-ordered sub-SegDSeeMp-clean-ordered sub-SeiSeeMp-clean-ordered  FORCE
distclean: sub-libUtil2-distclean-ordered sub-libExprEval-distclean-ordered sub-libCwp-distclean-ordered sub-libSegD-distclean-ordered sub-GxLib-distclean-ordered sub-SegDSeeMp-distclean-ordered sub-SeiSeeMp-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-libUtil2-install_subtargets-ordered sub-libExprEval-install_subtargets-ordered sub-libCwp-install_subtargets-ordered sub-libSegD-install_subtargets-ordered sub-GxLib-install_subtargets-ordered sub-SegDSeeMp-install_subtargets-ordered sub-SeiSeeMp-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libUtil2-uninstall_subtargets-ordered sub-libExprEval-uninstall_subtargets-ordered sub-libCwp-uninstall_subtargets-ordered sub-libSegD-uninstall_subtargets-ordered sub-GxLib-uninstall_subtargets-ordered sub-SegDSeeMp-uninstall_subtargets-ordered sub-SeiSeeMp-uninstall_subtargets-ordered FORCE

sub-libUtil2-debug_ordered:
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile debug
sub-libExprEval-debug_ordered: sub-libUtil2-debug_ordered 
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile debug
sub-libCwp-debug_ordered: sub-libExprEval-debug_ordered 
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile debug
sub-libSegD-debug_ordered: sub-libCwp-debug_ordered 
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile debug
sub-GxLib-debug_ordered: sub-libSegD-debug_ordered 
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile debug
sub-SegDSeeMp-debug_ordered: sub-GxLib-debug_ordered 
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile debug
sub-SeiSeeMp-debug_ordered: sub-SegDSeeMp-debug_ordered 
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile debug
debug: sub-libUtil2-debug_ordered sub-libExprEval-debug_ordered sub-libCwp-debug_ordered sub-libSegD-debug_ordered sub-GxLib-debug_ordered sub-SegDSeeMp-debug_ordered sub-SeiSeeMp-debug_ordered

sub-libUtil2-release_ordered:
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile release
sub-libExprEval-release_ordered: sub-libUtil2-release_ordered 
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile release
sub-libCwp-release_ordered: sub-libExprEval-release_ordered 
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile release
sub-libSegD-release_ordered: sub-libCwp-release_ordered 
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile release
sub-GxLib-release_ordered: sub-libSegD-release_ordered 
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile release
sub-SegDSeeMp-release_ordered: sub-GxLib-release_ordered 
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile release
sub-SeiSeeMp-release_ordered: sub-SegDSeeMp-release_ordered 
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile release
release: sub-libUtil2-release_ordered sub-libExprEval-release_ordered sub-libCwp-release_ordered sub-libSegD-release_ordered sub-GxLib-release_ordered sub-SegDSeeMp-release_ordered sub-SeiSeeMp-release_ordered

sub-libUtil2-check_ordered:
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile check
sub-libExprEval-check_ordered: sub-libUtil2-check_ordered 
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile check
sub-libCwp-check_ordered: sub-libExprEval-check_ordered 
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile check
sub-libSegD-check_ordered: sub-libCwp-check_ordered 
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile check
sub-GxLib-check_ordered: sub-libSegD-check_ordered 
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile check
sub-SegDSeeMp-check_ordered: sub-GxLib-check_ordered 
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile check
sub-SeiSeeMp-check_ordered: sub-SegDSeeMp-check_ordered 
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile check
check: sub-libUtil2-check_ordered sub-libExprEval-check_ordered sub-libCwp-check_ordered sub-libSegD-check_ordered sub-GxLib-check_ordered sub-SegDSeeMp-check_ordered sub-SeiSeeMp-check_ordered

sub-libUtil2-benchmark_ordered:
	@if not exist libUtil2\ mkdir libUtil2\ & if not exist libUtil2\ exit 1
	cd libUtil2\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libUtil2\libUtil2.pro ) && $(MAKE) -f Makefile benchmark
sub-libExprEval-benchmark_ordered: sub-libUtil2-benchmark_ordered 
	@if not exist libExprEval\ mkdir libExprEval\ & if not exist libExprEval\ exit 1
	cd libExprEval\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libExprEval\libExprEval.pro ) && $(MAKE) -f Makefile benchmark
sub-libCwp-benchmark_ordered: sub-libExprEval-benchmark_ordered 
	@if not exist libCwp\ mkdir libCwp\ & if not exist libCwp\ exit 1
	cd libCwp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libCwp\libCwp.pro ) && $(MAKE) -f Makefile benchmark
sub-libSegD-benchmark_ordered: sub-libCwp-benchmark_ordered 
	@if not exist libSegD\ mkdir libSegD\ & if not exist libSegD\ exit 1
	cd libSegD\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\libSegD\libSegD.pro ) && $(MAKE) -f Makefile benchmark
sub-GxLib-benchmark_ordered: sub-libSegD-benchmark_ordered 
	@if not exist GxLib\ mkdir GxLib\ & if not exist GxLib\ exit 1
	cd GxLib\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\GxLib\GxLib.pro ) && $(MAKE) -f Makefile benchmark
sub-SegDSeeMp-benchmark_ordered: sub-GxLib-benchmark_ordered 
	@if not exist SegDSeeMp\ mkdir SegDSeeMp\ & if not exist SegDSeeMp\ exit 1
	cd SegDSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SegDSeeMp\SegDSeeMp.pro ) && $(MAKE) -f Makefile benchmark
sub-SeiSeeMp-benchmark_ordered: sub-SegDSeeMp-benchmark_ordered 
	@if not exist SeiSeeMp\ mkdir SeiSeeMp\ & if not exist SeiSeeMp\ exit 1
	cd SeiSeeMp\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\MyFiles\code\SeiSee\SeiSeeMp\SeiSeeMp.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-libUtil2-benchmark_ordered sub-libExprEval-benchmark_ordered sub-libCwp-benchmark_ordered sub-libSegD-benchmark_ordered sub-GxLib-benchmark_ordered sub-SegDSeeMp-benchmark_ordered sub-SeiSeeMp-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

